apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPMachineTemplate
metadata:
  name: {{ .Values.cluster.name }}-control-plane
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      image: {{ .Values.cpMachines.image }}
      instanceType: {{ .Values.cpMachines.instanceType }}
      subnet: {{ .Values.cpMachines.subnet }}
      publicIP: {{ .Values.cpMachines.publicIP }}
