apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: {{ .Values.cluster.name }}-control-plane
  namespace: {{ .Release.Namespace }}
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: gce
          feature-gates: DisableCloudProviders=false,DisableKubeletCloudCredentialProviders=false
        timeoutForControlPlane: 20m0s
      controllerManager:
        extraArgs:
          allocate-node-cidrs: "false"
          cloud-provider: gce
          feature-gates: DisableCloudProviders=false,DisableKubeletCloudCredentialProviders=false
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: gce
          feature-gates: DisableCloudProviders=false,DisableKubeletCloudCredentialProviders=false
        name: '{{ "{{" }} ds.meta_data.local_hostname.split(".")[0] {{ "}}" }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: gce
          feature-gates: DisableCloudProviders=false,DisableKubeletCloudCredentialProviders=false
        name: '{{ "{{" }} ds.meta_data.local_hostname.split(".")[0] {{ "}}" }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: GCPMachineTemplate
      name: {{ .Values.cluster.name }}-control-plane
  replicas: 1
  version: {{ .Values.kubernetes_version }}
