apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ .Values.cluster.name }}-md-0
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: gce
            feature-gates: DisableCloudProviders=false,DisableKubeletCloudCredentialProviders=false
          name: '{{ "{{" }} ds.meta_data.local_hostname.split(".")[0] {{ "}}" }}'
