apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ .Values.cluster.name }}-md-0
  namespace: {{ .Release.Namespace }}
spec:
  clusterName: {{ .Values.cluster.name }}
  replicas: 1
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ .Values.cluster.name }}-md-0
      clusterName: {{ .Values.cluster.name }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: GCPMachineTemplate
        name: {{ .Values.cluster.name }}-md-0
      version: {{ .Values.kubernetes_version }}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
